version: '3.8'
services:
  api:
    container_name: helpdesk-api
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      QUARKUS_PROFILE: prod
    volumes:
      - ./privateKey.pem:/app/privateKey.pem:ro
      - ./publicKey.pem:/app/publicKey.pem:ro
    restart: unless-stopped
