# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:helpdesk}
quarkus.datasource.password=${DB_PASSWORD:helpdesk}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:helpdesk}

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://helpdesk.si
smallrye.jwt.sign.key.location=privateKey.pem

# OpenAPI
quarkus.smallrye-openapi.info-title=HelpDesk API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=REST API for the HelpDesk mobile + operator web app
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# CORS (for browser operator client)
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
